// Generated by gencpp from file my_turtlebot2_training/openai_ros.msg
// DO NOT EDIT!


#ifndef MY_TURTLEBOT2_TRAINING_MESSAGE_OPENAI_ROS_H
#define MY_TURTLEBOT2_TRAINING_MESSAGE_OPENAI_ROS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_turtlebot2_training
{
template <class ContainerAllocator>
struct openai_ros_
{
  typedef openai_ros_<ContainerAllocator> Type;

  openai_ros_()
    : rosds(0.0)  {
    }
  openai_ros_(const ContainerAllocator& _alloc)
    : rosds(0.0)  {
  (void)_alloc;
    }



   typedef float _rosds_type;
  _rosds_type rosds;





  typedef boost::shared_ptr< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> const> ConstPtr;

}; // struct openai_ros_

typedef ::my_turtlebot2_training::openai_ros_<std::allocator<void> > openai_ros;

typedef boost::shared_ptr< ::my_turtlebot2_training::openai_ros > openai_rosPtr;
typedef boost::shared_ptr< ::my_turtlebot2_training::openai_ros const> openai_rosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_turtlebot2_training::openai_ros_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_turtlebot2_training

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'my_turtlebot2_training': ['/home/yuya/simulation_ws/src/my_turtlebot2_training/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5eb6bf66b5eaa87e0e6f64597c745a4a";
  }

  static const char* value(const ::my_turtlebot2_training::openai_ros_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5eb6bf66b5eaa87eULL;
  static const uint64_t static_value2 = 0x0e6f64597c745a4aULL;
};

template<class ContainerAllocator>
struct DataType< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_turtlebot2_training/openai_ros";
  }

  static const char* value(const ::my_turtlebot2_training::openai_ros_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 rosds\n"
;
  }

  static const char* value(const ::my_turtlebot2_training::openai_ros_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rosds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct openai_ros_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_turtlebot2_training::openai_ros_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_turtlebot2_training::openai_ros_<ContainerAllocator>& v)
  {
    s << indent << "rosds: ";
    Printer<float>::stream(s, indent + "  ", v.rosds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_TURTLEBOT2_TRAINING_MESSAGE_OPENAI_ROS_H
